version: "3"
services:
  bot:
    build: 
      context: .
      dockerfile: dockerfile
    volumes:
      - "./config.prod.json:/app/config.json"
      - "./data:/data"
      - "./templates:/templates"