version: "3"
services:
  redis: 
    image: redis:7-bullseye

    ports:
      - 127.0.0.1:6379:6379
      
  database:
    image: postgres:14-bullseye
    
    environment:
      POSTGRES_PASSWORD: masterkey
      PGDATA: /var/lib/postgresql/data/secretary/
    ports:
      - "5432:5432"
    volumes: 
      - "./database/init-db/:/docker-entrypoint-initdb.d"

  bot:
    build: 
      context: .
      dockerfile: ./Secretary.Console/dockerfile
    
    volumes:
      - "./config.prod.json:/app/config.json"
      - "./data:/data"
      - "./templates:/templates"
      - "./calendars:/calendars"
      - "/var/log/secretary/bot:/logs"
      - "/tmp/secretary:/tmp"

    depends_on:
      - redis
      - database

  panel-backend:
    build: 
      context: .
      dockerfile: ./Secretary.Panel/dockerfile
    
    ports:
      - 127.0.0.1:38080:80
      
    volumes:
      - "./config.prod.json:/app/config.json"

    depends_on:
      - database
      - redis

  panel-frontend:
    build: 
      context: .
      dockerfile: ./Secretary.Frontend/dockerfile
    
    volumes:
      - "/var/log/secretary/panel:/logs"
    
    ports:
      - 127.0.0.1:30080:80

    depends_on:
      - panel-backend