version: "3"
services:
  redis: 
    image: redis:7-bullseye

    ports:
      - 6379:6379
      
  database:
    image: postgres:14-bullseye
    
    environment:
      POSTGRES_PASSWORD: masterkey
      PGDATA: /var/lib/postgresql/data/secretary/
    ports:
      - "5432:5432"
    volumes: 
      - "./database/init-db/:/docker-entrypoint-initdb.d"

  bot:
    build: 
      context: .
      dockerfile: dockerfile
    
    volumes:
      - "./config.prod.json:/app/config.json"
      - "./data:/data"
      - "./templates:/templates"
      - "/var/log/Secretary:/logs"
      - "/tmp/Secretary:/tmp"

    depends_on:
      - redis
      - database