name: Publish Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "master" ]
    
  workflow_dispatch:
    inputs:
      tags:
        description: 'Run Publish'  
        
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  BOT_IMAGE_NAME: secretary
  FRONTEND_IMAGE_NAME: panel-frontend
  BACKEND_IMAGE_NAME: panel-backend


jobs:
  run-tests:
    uses: ./.github/workflows/unit-tests.yml

  build-and-push-bot:
    needs: [run-tests]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build . --file Secretary.Console/dockerfile --tag $BOT_IMAGE_NAME

      - name: Tag image
        run: docker tag $BOT_IMAGE_NAME ghcr.io/${{ github.actor }}/$BOT_IMAGE_NAME:latest

      - name: Push client image
        run: docker push ghcr.io/${{ github.actor }}/$BOT_IMAGE_NAME:latest

  build-and-push-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build . --file Secretary.Frontend/dockerfile --tag $FRONTEND_IMAGE_NAME

      - name: Tag image
        run: docker tag $FRONTEND_IMAGE_NAME ghcr.io/${{ github.actor }}/$FRONTEND_IMAGE_NAME:latest

      - name: Push client image
        run: docker push ghcr.io/${{ github.actor }}/$FRONTEND_IMAGE_NAME:latest

  build-and-push-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build . --file Secretary.Panel/dockerfile --tag $BACKEND_IMAGE_NAME

      - name: Tag image
        run: docker tag $BACKEND_IMAGE_NAME ghcr.io/${{ github.actor }}/$BACKEND_IMAGE_NAME:latest

      - name: Push client image
        run: docker push ghcr.io/${{ github.actor }}/$BACKEND_IMAGE_NAME:latest