name: Secretary Panel Frontend Tests

on:
  push:
    branches: [ "master", "develop" ]

  workflow_dispatch:
    inputs:
      tags:
        description: 'Run Tests'  

  workflow_call:

jobs:
  check-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    defaults:
      run:
        working-directory: ./Secretary.Frontend  

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - run: npm run build --if-present

      - run: npm test --  --browsers=ChromeHeadless --watch=false --code-coverage