name: Secretary Panel Backend Tests

on:
  push:
    branches: [ "master", "develop" ]

  workflow_dispatch:
    inputs:
      tags:
        description: 'Run Tests'  

  workflow_call:

jobs:
  dotnet-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build Secretary.Panel.Tests --no-restore

    - name: Copy Config For Panel Tests
      run: cp test-configs/config.json Secretary.Panel.Tests/bin/Debug/net6.0/config.json

    - name: Test
      run: dotnet test Secretary.Panel.Tests --no-build --verbosity normal