name: Secretary Unit Tests

on:
  push:
    branches: [ "master", "develop" ]

  workflow_dispatch:
    inputs:
      tags:
        description: 'Run Tests'  

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Copy Config For Documents Tests
      run: cp test-configs/config.json secretary.documents.tests/bin/Debug/net6.0/config.json
    - name: Copy Config For Telegram Tests
      run: cp test-configs/config.json secretary.telegram.tests/bin/Debug/net6.0/config.json
    - name: Copy Config For Yandex Tests
      run: cp test-configs/config.json secretary.yandex.tests/bin/Debug/net6.0/config.json
    - name: Test
      run: dotnet test --no-build --verbosity normal
